version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # LocalStack メインエンドポイント
      - "4510-4559:4510-4559" # その他のサービス用ポート
    environment:
      - SERVICES=lambda,apigateway,dynamodb,logs
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DYNAMODB_TABLE=ISSUER_SESSION_DYNAMO
      - DYNAMODB_ENDPOINT="http://localstack:4566"
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./shell:/app/shell
