version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    env_file: ../.env.lambda.local
    networks:
      - dev-network
    working_dir: /workspace
    ports:
      - "3000:3000"
    init: true

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-verifier-frontend
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    networks:
      - dev-network

networks:
  dev-network:
    name: hono-lambda-dynamodb_devcontainer_dev-network
    driver: bridge

# 環境変数
# DYNAMODB_ENDPOINT=http://dynamodb-${COMPOSE_PROJECT_NAME}:8000

